#!/bin/sh
set -e

if [ $# -eq 0 ]; then 
	# mysql commands with passwords and options
	myclidbroot="mysql -uroot -P$LIME_DB_PORT -h$LIME_DB_HOST -p$MYSQL_ROOT_PASSWORD"
	myclidbuser="mysql -u$LIME_DB_USER -P$LIME_DB_PORT -h$LIME_DB_HOST -p$LIME_DB_PASSWORD"
	myclisqlshow="mysqlshow -uroot -P$LIME_DB_PORT -h$LIME_DB_HOST -p$MYSQL_ROOT_PASSWORD"

	# Wait until db host gets available
	dbavailable=0
	while [ $dbavailable -eq 0 ]; do
		sleep 2
		$myclidbroot -e "show processlist;" > /dev/null 2>&1 && dbavailable=1
	done

	# Check if DB exists:
	dbexists=0
	$myclisqlshow | sed '1,/Databases/d' | awk '{print $2}' | grep $LIME_DB_NAME > /dev/null 2>&1 && dbexists=1

	if [ $dbexists -eq 0 ]; then 
		  echo "Database $LIME_DB_NAME does not exist."
		  echo "Creating and initializing." 
		  $myclidbroot -e "CREATE DATABASE ${LIME_DB_NAME};"
		  $myclidbroot -e "CREATE USER IF NOT EXISTS ${LIME_DB_USER}@'%' IDENTIFIED BY '${LIME_DB_PASSWORD}';"
		  $myclidbroot -e "ALTER USER ${LIME_DB_USER}@'%' IDENTIFIED BY '${LIME_DB_PASSWORD}';"
		  $myclidbroot -e "GRANT ALL PRIVILEGES ON ${LIME_DB_NAME}.* TO ${LIME_DB_USER}@'%';"
		  $myclidbroot -e "FLUSH PRIVILEGES;"
		  cd /var/www/html/application/commands
		  php console.php install "${LIME_ADMIN}" "${LIME_ADMIN_PW}" "Administrator (local)" "${LIME_ADMIN_MAIL}" verbose
		  # mangle the database
		  if [ -e /usr/share/linuxmuster-limesurvey/changes.sql ]; then
		      $myclidbuser ${LIME_DB_NAME} < /usr/share/linuxmuster-limesurvey/changes.sql
		  fi
 	 else
		  echo "Database $LIME_DB_NAME exists."
		  echo "Setting password as specified in docker-compose.yml."
		  $myclidbroot -e "CREATE USER IF NOT EXISTS ${LIME_DB_USER}@'%' IDENTIFIED BY '${LIME_DB_PASSWORD}';"
		  $myclidbroot -e "ALTER USER ${LIME_DB_USER}@'%' IDENTIFIED BY '${LIME_DB_PASSWORD}';"
		  $myclidbroot -e "GRANT ALL PRIVILEGES ON ${LIME_DB_NAME}.* TO ${LIME_DB_USER}@'%';"
		  $myclidbroot -e "FLUSH PRIVILEGES;"
  	fi

	# Start apache
	apache2-foreground
else
	# Execute given command
	exec "$@"
fi

